//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreePlus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreePlus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to varying vec3 vPosition;\nvoid main() {\n\tgl_FragColor = vec4( vPosition * 2.0, 1.0 );\n}.
        /// </summary>
        internal static string FragmentShader {
            get {
                return ResourceManager.GetString("FragmentShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Three_LightAmbient {
            get {
                object obj = ResourceManager.GetObject("Three_LightAmbient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Three_LightDirectional {
            get {
                object obj = ResourceManager.GetObject("Three_LightDirectional", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Three_LightHemisphere {
            get {
                object obj = ResourceManager.GetObject("Three_LightHemisphere", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Three_LightLine {
            get {
                object obj = ResourceManager.GetObject("Three_LightLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Three_LightPoint {
            get {
                object obj = ResourceManager.GetObject("Three_LightPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Three_LightSpot {
            get {
                object obj = ResourceManager.GetObject("Three_LightSpot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Three_MaterialAnalytical {
            get {
                object obj = ResourceManager.GetObject("Three_MaterialAnalytical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Three_MaterialFlat {
            get {
                object obj = ResourceManager.GetObject("Three_MaterialFlat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Three_MaterialLambert {
            get {
                object obj = ResourceManager.GetObject("Three_MaterialLambert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Three_MaterialPhong {
            get {
                object obj = ResourceManager.GetObject("Three_MaterialPhong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Three_MaterialPhysical {
            get {
                object obj = ResourceManager.GetObject("Three_MaterialPhysical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * @license
        /// * Copyright 2010-2021 Three.js Authors
        /// * SPDX-License-Identifier: MIT
        /// */
        ///const REVISION = &apos;131&apos;;
        ///const MOUSE = { LEFT: 0, MIDDLE: 1, RIGHT: 2, ROTATE: 0, DOLLY: 1, PAN: 2 };
        ///const TOUCH = { ROTATE: 0, PAN: 1, DOLLY_PAN: 2, DOLLY_ROTATE: 3 };
        ///const CullFaceNone = 0;
        ///const CullFaceBack = 1;
        ///const CullFaceFront = 2;
        ///const CullFaceFrontBack = 3;
        ///const BasicShadowMap = 0;
        ///const PCFShadowMap = 1;
        ///const PCFSoftShadowMap = 2;
        ///const VSMShadowMap = 3;
        ///const FrontSide = 0;
        ///const BackSide = 1;
        ///const  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string three_module {
            get {
                return ResourceManager.GetString("three_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import * as THREE from &apos;https://threejsfundamentals.org/threejs/resources/threejs/r127/build/three.module.js&apos;;.
        /// </summary>
        internal static string ThreeJsHeader {
            get {
                return ResourceManager.GetString("ThreeJsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uniform float time;\nvarying vec3 vPosition;\nvoid main() {\n\tvPosition = position;\n\tvPosition.x += sin( time + vPosition.z * 4.0 ) / 4.0;\n\tvPosition.y += cos( time + vPosition.z * 4.0 ) / 4.0;\n\tgl_Position = projectionMatrix * modelViewMatrix * vec4( vPosition, 1.0 );\n}.
        /// </summary>
        internal static string VertexShader {
            get {
                return ResourceManager.GetString("VertexShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class VRButton {
        ///
        ///	static createButton( renderer, options ) {
        ///
        ///		if ( options ) {
        ///
        ///			console.error( &apos;THREE.VRButton: The &quot;options&quot; parameter has been removed. Please set the reference space type via renderer.xr.setReferenceSpaceType() instead.&apos; );
        ///
        ///		}
        ///
        ///		const button = document.createElement( &apos;button&apos; );
        ///
        ///		function showEnterVR( /*device*/ ) {
        ///
        ///			let currentSession = null;
        ///
        ///			async function onSessionStarted( session ) {
        ///
        ///				session.addEventListener( &apos;end&apos;, onSessionEnded );
        ///
        ///				await renderer.xr.setSe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VRButton {
            get {
                return ResourceManager.GetString("VRButton", resourceCulture);
            }
        }
    }
}
